name: Build Image and Run Image Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker (correct version)
      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          docker_version: '20.10.7'

      # Step 3: Build Docker image (fixed working directory issue)
      - name: Build Docker Image
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -al
          echo "Building Docker image..."
          docker build -f ${{ github.workspace }}/Dockerfile -t pygoat_app:latest ${{ github.workspace }}

      # Step 4: Run Docker Scout Scan (image vulnerability check)
      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.0
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PWD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif

      # Step 5: Upload Artifact (scan report)
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-findings
          path: scout-report.sarif
